### PR TITLE
PEP 8 Changes. Nodeconection.run -> line.encode() remove beacause soc…

### PR DESCRIPTION
**Pull request by SamuelHaidu**
New file struc

PEP 8 code changes

line.encode() in sock read remove because sock.recv() return bytes no str

### CODE REVIEW

**Comment by macsnoeren** [comment]
Hi Samuel,
Nice work you did and nice to see you dig into the project. Thanks for the merge request. I need to look into it further, so if you have further comments, please share.
Regards, Maurice

**Comment by macsnoeren** [comment]
I have merged your things to my development branch. I will work on it and push it to the master eventually. Thanks! The handshake will be out, while that will be an implementation part of the p2p application that uses this Node.

**Comment by SamuelHaidu** [comment]
Hello macsnoeren!

I do a lot of modifications, this also made the README.md obsolete. We need to change this "mini doc".

I change the call back event name (more readable)
I remove the visualization (i think you do this to use in your class and not working anymore)
I remove some redundant methods that just return "self.attribute". For this just use "instance.attribute".

About the handshake implementation: 
I see in the code a `# TODO: Startup first communication in which the details of the node is communicated`
So i implement a little handshake that send: 
"message_protocol"  <- The name of your library
"message_format" <- Json, because this library just support json encode data
"id": before ids are local and now in the handshake send your ids to sync
"host", "port" the ip and port that the node is listening. This is the most important if you want to implement a discover the node can send the host and port to other node connect see this example:

node 005 connect to node 004 and send:
node 005: hey node 004 you have the file "book.pdf"?
node 004: no, but I am connect to others nodes and I can search for you

node 004 send to the nodes:
node 004 someone have the 'book.pdf'
node 001: yes, i have
node 004 ok, thanks

node 004 send to node 005:
node 004: hey the "node 1 (ip:port)" has the file 'book.pdf' connect with him.
node 005: ok, tks :)

If the message_protocol and message_format are not equal the connect is close to prevent bad connections.

I know that we need a more robust handshake, but in this case the libary forces a protocol just works with json format. 
This libary needs changes in how are send the messages to be more generic and flex.

My idea is change the message format to something more flex, that let choose the user send dicts, files or pure text.

**Comment by macsnoeren** [comment]
Thanks for your note. I have finished with the work and pushed everything to the master branch. Working from development now, much better :). You have the idea! And that is great. I removed the handshake, because it is application specific. However, I implemented that the nodes exchanged their id's. Just for basic functionality. 

I agree to the fact that the basic functionality expect JSON format is not according to my idea as described above. So, it must be deleted, so others can choose what to use. I have closed the pull request, because I have added your changed to the master myself.

**Comment by SamuelHaidu** [comment]
Cool :)
I am very happy and grateful to accept

**Pull request closed without merging**
