### PR TITLE
Fix message system

### PR DESCRIPTION
**Pull request by SamuelHaidu**
**Remake the EOT:**  
before using "-TSN" string now use 0x04 UTF-8/ASCII standard char.

**Fix the message system:**  
Remove the JSON mode it resulted in several bugs. Now are possible send/receive JSON, pure text (any string) or bytes (anything like a bin files or blockchain blocks).

Now the lib is more generic to use any type of data with a bult-in facilities (encode to json or str)

### CODE REVIEW

**Comment by macsnoeren** [comment]
It is a great update, but I have reworked the code largely. I will make the changes you have proposed directly into the latest version. Make sure you update to the newest version as well. Thanks for your good insights!

**Comment by macsnoeren** [comment]
I have merged all your changes (with some minor changes in naming convention). Currently, development contains the latest status. The software is more mature: classes in seperate files and unit tests written (run: python setup.py test). It will run three tests. One of the test is based on your complete_test. Make sure your are up-to-date, while there have been major changes. See the examples and documentation for more information.

**Comment by SamuelHaidu** [comment]
Very good updates in code manly the unittest. Tks a lot

**Comment by macsnoeren** [comment]
Thanks :)! I have added a new unit test for communication. Unfortunately, I am not able to test sending bytes over the node channel. Maybe you can help me on that. I have updated development at this moment.

**Pull request closed without merging**
